version: 2
jobs:
  build:
    docker:
      - image: php:7.2-cli-alpine3.7
    working_directory: /app
    steps:
      - run: apk add --no-cache curl git tar gzip
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Building and Pushing Docker images
          command: |
            docker build -t yoangrigorov/thesis-builder:latest .
            docker login -u ${DOCKER_ID} -p ${DOCKER_SECRET}
            docker push yoangrigorov/thesis-builder:latest
